### PR TITLE
Corona glass scene after hospital

### LINKED ISSUE #153: Discolevel
What should we do here? Do not show the infection status? Wind up some story why we can see infected?

### PR DESCRIPTION
**Pull request by maccxs**
I propose the following:
The user is left the choice to test the glasses or not. If they accept, they see the infected in the disco level and the glasses are broken in a further scene afterwards. If not, they don't see the infected in the disco level. Should such a variable be stored in the level settings? I will only produce the scenes first, no the logic behind them since they need to be integrated with the new animations anyway.

### CODE REVIEW

**Comment by maccxs** [comment]
grafik

**Comment by maccxs** [comment]
grafik

**Comment by maccxs** [comment]
grafik

**Comment by maccxs** [comment]
I am so far done with the scenes. As always feedback is greatly appreciated and welcome and I am not set on the design or the course of action :-)

**Comment by maccxs** [comment]
grafik

**Comment by maccxs** [comment]
grafik

**Comment by holke** [comment]
These screens look really great and funny.

I am unsure about giving the user the choice though.
I think the disco level is more or less impossible without seeing the infected, so the user would get frustrated if he choose not to use the glasses and could possibly never make it to the end of the game.

**Comment by maccxs** [comment]
Ok, mmh, I really liked the idea of giving the user the choice. But maybe you are right. Additionally with no choice there is less to do and we want this too be released soon. I am still not 100% convinced though. ;-)

**Comment by maccxs** [comment]
grafik

**Comment by maccxs** [comment]
@holke How to proceed?
* You merge the animation branch and the canvasdesign into master
* I will make a new branch from master with new scenes here?
* In disco level I will then also use prefab with glasses AND mask
* You do the animation part for the three scenes (I would love to try out myself but we should maybe take the most time-saving route)?

**Pull request merged**
