### PR TITLE
More levels

### LINKED ISSUE #61: More levels
Add more levels to the game.

Ideas:

Level 1 (the current state): Move around and try not o get infected. Maybe we can end this after n seconds? like: Survive for 1 Minute?

Level 2: Move to you house at the opposite end of the map.

Level 3: There is a supermarket on the map. Go there and get back to your house again.
The supermarket should be visited by other NPCs too.

Level 4 (sophisticated, needs new map): Inside the supermarket. Get item X and get out. The NPCs move along the aisles.

Do you have more ideas? Please feel free to add here or to the [discussion thread.]( https://github.com/orgs/youvsvirus/teams/game-developers)

### LINKED ISSUE #74: Give the human and NPCs a home
Add a picture of a house or better multiple houses, where the player and the NPCs can live.
These pictures can then be used in level design.

### PR DESCRIPTION
**Pull request by holke**
Prepare for multiple level usage.

Changed end game controller to end level controller.
Implemented base class for end level controller, so
that each level can implement its own end conditions.

You do not need to merge this, but i would love to hear your feedback on this.

### CODE REVIEW

**Comment by holke** [comment]
We now have a second level to try out.
It currently does nothing different than the first (except for a supermarket ok the map), but demonstrates that multiple levels work and serves as a template to build levels.

**Comment by maccxs** [comment]
Moin, really happy that you took this on :-) Fits to my endeavour of building the next level really well! So I have only had a very small look at it, just tried it out. The game ended early in the second level, although no end condition was met. We already had that problem with the end game controller; see the branch and comments there. (and closed issue) Sorry to just leave this quick small dirty feedback, but I have a family date in 1 minute. Will look a lot more later.

**Comment by holke** [comment]
Thank you for the feedback.
The second level is supposed to end early this is not a bug.
If you look in the editor at the endlevelcontroller entity, an end time of (I think) 20 seconds is set there.
Set it to 0 for the same end conditions as the other level.
Have fun with your family ;)

**Comment by maccxs** [comment]
Hi, I think I like the structure with the EndGameController inheriting for each level from a base. :-)

**Comment by maccxs** [comment]
> 
> 
> Thy for the feedback.
> The second level is supposed to end early this is not a bug.
> If you look in the editor at the endlevelcontroller entity, an end time of (I think) 20 seconds is set there.
> Set it to 0 for the same end conditions as the other level.
> Have fun with your family ;)

Mmh, I don't see it. in that inherited class it says
public class EndLevelControllerLevel2 : EndLevelControllerBase
 {
 
 }
so nothing. Also noticed that the comment says The end level controller for level 1. which should be 2, of course. Did you mean something different?

**Comment by maccxs** [comment]
Ah, I see, you set it to 10s in the inspector. and in the script you say: everything as in the base class :-)

**Comment by maccxs** [comment]
What does this EventSystem do?

**Comment by maccxs** [comment]
Would it make sense to have a similar strucutre for the level initialization? The user will not always be allowed to set #npc and so on... Just a thought

**Pull request merged**
