### PR TITLE
Added player house prefab to levelmasks

### LINKED ISSUE #113: Levelmasks: make a prefab out of the player house so that the player can still get in and out

### PR DESCRIPTION
**Pull request by maccxs**
The player house
 * optional, not implemented yet: notifies the end level controller when the player is home
 * sets the player in the house depending on their condition
 * sets the player inside when space-key is pressed
 * sets the player outside when space-key is pressed

### CODE REVIEW

**Comment by maccxs** [comment]
After dinner I overhought my solution: I will have to stop the coroutines otherwise space always gets the player home.

**Comment by maccxs** [comment]
Now everything should be fine, hopefully.

**Comment by holke** [comment]
I like it :)
Looks good.

Somehow the hospital has vanished?

**Comment by maccxs** [comment]
Hi, the hospital was not there in the first place. I got some error when I
loaded your branch. Will this be a big problem to add again? Should I do
something? Also forgot to mention: In my opinion, it is nice if the house
can be roughly on the same place on the map as in the other levels.

Am Fr., 22. Mai 2020 um 16:22 Uhr schrieb holke <notifications@github.com>:

**Comment by holke** [comment]
Hi, 
yeah i just realized that i forgot to push the house picture. So sorry for the false alarm.
And yes, it was my idea to put the house at the same position, as you did in the supermarket level.

**Pull request merged**
