### PR TITLE
Added Smiley pictures to the end screen

### LINKED ISSUE #55: Improve end screen
After first release.

I think we could add the smiley pictures to the stats in the end screen.
This way we would also visually demonstrate the meaning of the numbers.
Example:

Exposed:                 57[Pic of the exposed smiley]

### PR DESCRIPTION
**Pull request by holke**
Next to the numbers in the end screen there are now Smileys to visually indicate the stats.

### CODE REVIEW

**Comment by holke** [comment]
Question: Do we have a place in the repo for data that we want to store but is not a Unity asset?
I had to make a pictures of an arrow, which i did as a vector graphic .svg file. To use it in unity i build a .png from it.
However, i want to keep  the original .svg in case we need to change something later.
Currently i store it at the same place as the .png which means that it shows up in the unity editor, showing two arrows (the png and svg). I rather store it somewhere, where it is not picked up by the unity editor...

**Comment by holke** [comment]
Please review #69  first and if you think it is good, i will put the svg files in the new additional data folder.

**Review by maccxs — COMMENTED** [review]
Moin,

it looks good and I only have technicalities.
* Acutally for Infected and Infected by you we count red smileys and blues smileys (e.g. the user lets the game end early, then sum Infected = sum blue + sum red). This is ok, I think, because these are the people carrying the virus. Maybe out red smiley / blue smiley as picture?
* The red of the smileys hurts my eyes. Maybe you can adopt it (works within the inspector --> color), so that it not so different from the red of the other virae? There is a pipette thingy, with which you can get the color of the virae and put it on top of the red smiley. Then it is still very red but less hurtful?

**Comment by holke** [comment]
Yeah i took the wrong colour there.
I think both issues would be resolved if i only took the blue smileys (this is also what we actually count: how often did a smiley get blue).

**Comment by maccxs** [comment]
Taking the blue smileys would be mathematically correct. But I think, it would be still missleading for the user who might ask: And what about the red ones? Where are those counted? It is already a little difficult with this construction and maybe it would be the chance to reference both.

**Comment by holke** [comment]
mhmmm, okay ill try it.

I thought about this option at first but decided against it, since it will clutter the end screen with smileys and make look too much.
But as i said, ill try it.

**Comment by holke** [comment]
I changed this now and added the player smiley (i thought i already had included it, but it got lost in a commit), and added blue and red smileys to infected.

In my opinion having blue and red smileys makes the end screen look really cluttered and chaotic now.
I rather not have the red smileys.
Please see 2fdb3ff for the alternative version.

**Comment by maccxs** [comment]
Hi, yes, I agree. If you did not make any further changes in https://github.com/youvsvirus/youvsvirus-unity/commit/2fdb3ffdc5fca0c7ccaad38eec771322454847a3, that can be merged into master.

**Pull request closed without merging**
