### PR TITLE
Refactor Create Humans

### PR DESCRIPTION
**Pull request by maccxs**
Divorced creation of grid and creation of humans.
Makes the creation  of humans  easier to understand and creation of grid too.
I also think that maybe we want to user our grid later on for e.g. placing
the homes of the smileys which should also not overlap.

### CODE REVIEW

**Review by holke — COMMENTED** [review]
Sorry for looking at this so late.
This is a good change, since the grid and humans got mixed up inside one class.
Could you merge this with master and then we can integrate it.

**Comment by maccxs** [comment]
Yes, I will do this after the merge of level 1, since otherwise it would yield conflicts and I would have to do it all over again. All current levels use this so I now have to change it in all of them.

**Comment by maccxs** [comment]
Merged the current status of Levelgethome.

**Comment by maccxs** [comment]
Oh great, now I made the changes for the Startsupermarket screen in this branch. Should not do everything at once. Should I try to get it in the other branch or do you want to test this one with the new creation of humans?

**Comment by holke** [comment]
WHen this is merged with the current master, we can integrate it

**Comment by maccxs** [comment]
Merged.

**Pull request merged**
