### PR TITLE
White border & UI scaling fixed

### LINKED ISSUE #36: White border around menu
There seems to be a white boarder around the menus, which is also different in size on different systems.
Here is a screenshot from @maccxs 

grafik

And here a screenshot from me:

WhiteBoundary

### PR DESCRIPTION
**Pull request by ghost**
I seperated the virae from the background image to avoid tearing the background, and made sure the background scales along with the viewport. No more white borders, no more empty screen edges. Resolves #36.

### CODE REVIEW

**Review by maccxs — COMMENTED** [review]
Hi!

Thanks for taking this on. Unfortunately I still have the blue borders (see Issue) in my scene.
grafik
The background and the virae were one picture, so I do not have them separately. I liked the "cleaner" look of the main menu and the ending menu before. This is what it looked like
grafik
This is what it looks now
grafik
Specifically
* I somehow liked the old blue, but that's not that important
* The YouVsVirus is not touched by the virae
* the darker blue of the canvas in the middle as opposed to the lighter blue around it
* The viruses do not touch the Canvas
Sorry, for nagging about these details.

**Comment by ghost** [comment]
You're right about the colors, I fixed that too, now. Also, I fixed the virae to scale with viewport size so they shouldn't overlap with anything. The layout still breaks for very small window sizes, but since the canvas size will be constant when embedded in the website, this shouldn't be a problem. 

I simply forgot about the borders in the scene. Working on it now. I'll try scaling the map along with the viewport as a quick fix, but for the future, I recommend we enable the camera to move along with the player. This would also solve the more profound problem: When the viewport windows is resized during play, the map barriers are not resized with it.

**Comment by ghost** [comment]
As far as I can see, the blue border only appears when the Unity player is set to "free aspect ratio" and the window is streched very wide. I feel any fix I could write for this would just be extremely dirty. 

I also just created a WebGL build, and the problem of map scaling is even more severe in the built version: When starting the game in small window mode and then going fullscreen, the viewport aspect ratio changes and the map barriers are not scaled along with it.

I recommend leaving this as it is right now. In the editor (which only concerns us as developers, anyway), just set the aspect ratio to 16:9 as a workaround. And for the website release, we should disable fullscreen mode for the first version. In the future, we will definitely have to solve this by allowing the camera to move.

**Comment by holke** [comment]
This looks good in my opinion.
The webgl build works with and without fullscreen for me.
When starting not full and then going full screen i can see white border stripes on the left and right.
But i think they are not too obvious and we can put this into release.

**Comment by maccxs** [comment]
Hey @FredyHennig, I merged the master which led to merge conflicts in the end scene. I tried to fix them but please check if I haven't overlooked any of your changes. Otherwise: Looks good now.

**Pull request merged**
