### PR TITLE
First try for random movement

### PR DESCRIPTION
**Pull request by maccxs**
Maybe there is a much better way do to this. At least it looks halfway smooth and seems to be a good velocity for the npcs. For more details see the code snippet.
@FredyHennig: Did i delete your "The sun rises..." message by accident?

### CODE REVIEW

**Comment by ghost** [comment]
@maccxs That message was just a debug message, I think I removed it myself.

**Comment by ghost** [comment]
Apart from the fact that the ghosts are still moving, it looks good :) But I'd expose minVel and maxVel as public variables to the editor instead of hard-coding them, so we can easily fine-tune them and also change them during runtime.

**Comment by ghost** [comment]
Currently, when the NPC is accelerating, its velocity grows exponentially. This way, when it is just below max velocity, it will easily jump up to almost 1.5 * maxVelocity. Maybe linear growth (= constant acceleration) is more sensible?

**Comment by maccxs** [comment]
Thanks for the improvements. Did not try them out yet but everything seems very sensible. I was playing around so much yesterday that I was just glad that it look halfway good.

**Comment by maccxs** [comment]
@FredyHennig : Checked out your improvements  in this branch - looking good. Introduced random initial velocity for npcs inbetween min and max. Implemented social distancing on top.  This works ok, I think. A social dist factor of 100% makes the circle collider radius now about 1.8 times as big as before. Some randomness introduced to make it look nicer.
Issues
* The player keeps more distance as well which seems a little unnatural but I mean, ok, it is really the npcs who keep their distance since I have not modified the player
* The distance to the wall has to be fixed, since the collider radius of the npcs also affects those

**Comment by ghost** [comment]
@maccxs I refactored the script to be directly attached to the NPC GameObject.

There is a tiny problem to your implementation: At a certain social distancing factor, the NPC's colliders grow larger than their infection radius. This way, noone will ever get infected any more. And below that point, I believe, the spread rate doesn't change at all because even with larger colliders, NPCs still are colliding just as often.

Maybe we should implement social distancing like in the python version, with decreased movement, for the time being? Later, we could try a more sophisticated approach, like a repelling force that still allows touching, but makes it harder.

**Comment by maccxs** [comment]
Hi, yes that is a problem. I tried to integrate the infection radius, but if I make the radius of the smileys too large, it really looks unnatural. I think we should still merge, because the social distancing is quite separate and does not break anything, but I will continue working on it then in a separate branch. This one has probably gotten large enough.

**Comment by maccxs** [comment]
@holke If you have a minute, maybe you yould merge this branch into the master and then (!) the other one. @FredyHennig and I have cross-reviewed the changes in this branch over the weekend.

**Pull request merged**
