### PR TITLE
The dead no longer interact with the living

### LINKED ISSUE #27: Take the dead out of the equation
Dead sprites should neither move nor collide

### PR DESCRIPTION
**Pull request by ghost**
Movement and collisions of dead NPCs and the player are now disabled. When a human dies, its rigidbody is simply removed from the simulation.

Also, I've introduced **Sorting Layers** for controlling Z-order of rendering. From lowest to highest:
1. Background
2. Dead
3. Living
4. Player

These changes are built on top of #28, so we should resolve that one first. Resolves #27 .

### CODE REVIEW

**Review by maccxs — COMMENTED** [review]
Hey, this works well! Good work! It would be great if you could explain in the line of the code that you changed, namely  
* GetComponent<Rigidbody2D>().simulated = false;
* GetComponent<SpriteRenderer>().sortingLayerName = "Dead";
what exactly these are doing and how they make the dead dead.  At a first glance this is not clear for a newbie developer.

**Comment by ghost** [comment]
@maccxs You're right, I've added the comments. I also realized that just disabling physics simulation for the dead is quite a dirty fix, so I've made it a little more thorough.

**Comment by maccxs** [comment]
Thanks, this is most helpful!

**Comment by maccxs** [comment]
This looks ready to be merged (after the other branch has been merged).

**Pull request merged**
