### PR TITLE
Margrit/design

### LINKED ISSUE #130: Canvas design for better readable text

### PR DESCRIPTION
**Pull request by maccxs**
- made canvas darker, enough?
- made start screen panels and script size smaller, this looks small now in unity but I think it will look good on the website and in full screen
- **I also uploaded the design to our test website** (the improved gameplay from exitkey is not integrated yet, this is just for design) - so please see how it looks in the browser

### CODE REVIEW

**Comment by holke** [comment]
Thanks for this update :)

Yes this seems dark enough now.
You also changed the red boxes to blue, which works as well.
The text size is good and not at all too small.

Only one critique: I prefered the confetti in the carnical screen over the ballons. ImO the balloons look more serious and hot half as funny.

**Comment by holke** [comment]
I sometimes need to press the continue button twice before it registeres...this may only be an artifact and resolve in the final version, but we should double check then.

**Comment by maccxs** [comment]
I can add the confetti again, but will leave the virae removed.

**Comment by maccxs** [comment]
> Yes this seems dark enough now.
> You also changed the red boxes to blue, which works as well.
> The text size is good and not at all too small.

The good thing is: Each canvas uses the same image with the same material, hence I only had to change this and all canvases were update automatically even the spress space and  the counter ones



EDIT by holke: Your comment got mixed up with the quote.

**Pull request merged**
