### PR TITLE
Levelgethome

### LINKED ISSUE #78: Implement level 1
The player needs to get home safely.

### PR DESCRIPTION
**Pull request by maccxs**
"level 1": levelgehome
* the player has to get home safely after carnival
* npcs do not reveal if they are infected or not
* only do so after player has been infected or ended game successfully
* player is set in the house when he gets there whether they are infected or not
* player fails as soons as they are infected but can play on in the background if need be

What I like:
* not having two separate endscreens but simply two canvas objects for failure and success
* not so many scenes necessary
* at the moment the end level controller handles all scripts for the buttons which is also nice since we do no have to have one script for this and one script for that

But maybe:
* have a separate script to handle all buttons? I don't mind the end level controller doing this, but perhaps it is not in the controller's best interest? If you wish it so, I can handle it separately.

### CODE REVIEW

**Comment by holke** [comment]
It’s a good idea to have one button handler script per level that implements all buttons.
Otherwise we get overflown by button scripts.

**Comment by holke** [comment]
I like this level.
The intro is nice and the fact that the state of the NPCs is not visible makes the game feel more realistic and changes the way i play (instead of running into the yellow smileys i need to avoid all smileys).

- The continue button at the end of the level currently leads to the begin if level 1 and not to level 2
- I would prefer if the message would not just say "you failed" but also state the reason. "You infected yourself with the virus".

**Comment by maccxs** [comment]
The text now says "Your are infected", introduced ButtonHandleBase.sc and ButtonHandleLevelgethome.cs to handle scripts separately from endgame control.

**Comment by maccxs** [comment]
The continue button just leads to some scene which will be used as the intro for level 2. For me this is not the begin of level 1 (as you wrote) but the end of level 1. Would be weird if it was something different for you. This is just a place holder.

**Comment by holke** [comment]
okayyyyyy,
So when i am on the end screen of level 1 that prints out the stats and press Continue it brings me right back into level 1. Not the intro screen but the direct level that i have to play.

This end screen is weirdly named "StartSceenLevelsupermarket" and its continue button leads to
YouVsVirus_Levelgethome.

**Pull request merged**
