### PR TITLE
A little zoom animation for the house in gethome level

### LINKED ISSUE #150: Add an animation for the house
The player house just have a little animation at the start of each (or some) levels to make it easier to be spotted.

### PR DESCRIPTION
**Pull request by holke**
This is my first try of an intro animation of the house.
Was this what you had in mind?

Please try this from the StartScreen of the gethome level.

### CODE REVIEW

**Comment by maccxs** [comment]
Hey, this looks great! Only minor thing: The house is normally very neatly aligned with the screen bound which is no longer the case. Bute maybe I am mistaken and I only now reallized it.

**Comment by holke** [comment]
mhmm, i thought i was very careful about not changing the houses position. Have to double check this.

**Comment by holke** [comment]
TODO: do the same with the hospital

**Comment by holke** [comment]
I added the animation for the hospital.

In my opinion this is done now.

**Comment by maccxs** [comment]
Hey, this looks good and can be merged or integrated.

**Pull request merged**
