### PR TITLE
Margrit/level4

### PR DESCRIPTION
**Pull request by maccxs**
Added a party level where you have to get you wasted friend home safely. You don't have to merge but feedback is highly appreciated. The difficulty is to set the infection just right, so it is hard to rescue the friend but not impossible.
**Note**
* best played from YouVsVirus_Level2 to check out all directions for the user
* make sure on the top right of unity to unmute your audio since there is music at the party of course

### CODE REVIEW

**Comment by holke** [comment]
Haha, i love it xD

It seems a bit too difficult currently, since you have to move through the ball of smileys and on the way back almost all smileys in their are infected so that there is no way out.

Maybe we could add a proper dancefloor to the map, which is like 90% the size of the current smiley ball and have an area around that which is a little less crowded.

**Comment by maccxs** [comment]
> 
> 
> Haha, i love it xD
> 
> It seems a bit too difficult currently, since you have to move through the ball of smileys and on the way back almost all smileys in their are infected so that there is no way out.
> 
> Maybe we could add a proper dancefloor to the map, which is like 90% the size of the current smiley ball and have an area around that which is a little less crowded.

I was actually afraid that it is too easy. It is always a little dependent on probability so every try is different. My familly managed on average in three tries to get Jeff out. If it is too easy there is no challenge. I like the idea with the dancefloor.

**Comment by holke** [comment]
Okay, that is a good point.

Thinking about this again, what bothered me was that even if you see that everybody is infected/sick you have no other chance to end the level except getting yourself infected.
Maybe we can add an option "Give up" or something? So that the level is not won, but you do not have to infect yourself deliberately?

**Comment by maccxs** [comment]
I undestand. However, if this were a real life situation, giving up would not be a possibility. You would just head for the exit (since in real life you just don't see that people are infected). We could still make it so that the ESC or other key just ends the current level with failure.

**Comment by holke** [comment]
We can make it that heading to the exit is always possible.
But when you exit without Jeff, the level is lost.

**Comment by maccxs** [comment]
Have you managed to get him out yet?
* One thing is yet missing: If you get infected and your friend does not, it is still counted as success. Will have to add this.
* I would love to add some dance lights to the scene but it's not as easy as I thought it might be.

**Comment by maccxs** [comment]
We need a better name for Jeff that sounds equally good in German and in English. I only thought of Alex but this is just no a good fit.

**Comment by maccxs** [comment]
Jeff could also be a woman

**Comment by holke** [comment]
Tom?
Sandra?
Peter?
Kevin?
Schaqueline-Schantall?

**Comment by holke** [comment]
Actually Alex is quite good since: It could be a man or woman and works in both languages.

**Comment by maccxs** [comment]
Yes, but my husband would be offended. Sandra is not so bad. Kevin also good. The header can already exit, we just check that he brought his friend and that the friend ist not infected. The infection check for the player is missing.

**Comment by holke** [comment]
Call him "Alex(Not Margrits husband)" then?

**Comment by maccxs** [comment]
ha, ha

**Comment by holke** [comment]
Ok, so do you want to integrate the dance floor before i merge?

**Comment by maccxs** [comment]
No, I don't. These are small changes that I could take on later.

**Comment by holke** [comment]
Could you please merge the current master into this branch?
I will then integrated it.

**Comment by maccxs** [comment]
Hey, merged the master. I also build the webgl which worked including music. Because of the screen resolution the bar is cut of but this will be fixed (very hopefully) when integrating the new camera fix. So please merge and then I will set the camera right for all scenes in the master in a new branch.

**Comment by holke** [comment]
Alright, thx for the update. Will check and merge.

**Comment by holke** [comment]
I Love it.

I noticed 2 things:

1. The player cant stay still since Jeff keeps pushing. I dont know if this is intentional, but we should keep it. It feels realistiv behaviour for a drunk friend.
2. i tried the tactic to let everybody get infected and become immune, however up to one single smiley all stayed blue. Is this intentional? 
If it is, I would also keep it, since a) its a dirty tactic to get everbody infected and shouldnt be allowed and b) the user can imagine that the disco level happens on a different time scale. It is not logical for somebody to get infected, sick and immune again, all while staying for one night at the disco.

**Pull request merged**
