### PR TITLE
Margrit/fix resolution

### LINKED ISSUE #82: Make all screen live in the same space
So we do not have to do so much dragging and scaling inbetween working on the scenes, and it's just more intuitive.

### PR DESCRIPTION
**Pull request by maccxs**
This is the current master branch with fixed resolution in all scenes. I explained the usage in the game and during build here https://github.com/youvsvirus/youvsvirus-unity/wiki/Build-and-camera-resolution

### CODE REVIEW

**Comment by holke** [comment]
Does this include changes from #88 or is it independent from it?

**Comment by maccxs** [comment]
This is based on the principles of #88 but it is independent of it. When this here is merged, we can delete the draft pull request #88. It mainly applies all script for the camera in #88 and uses them for all screens here. However, some addtions and fixes were still necessary.

**Comment by holke** [comment]
So, does this also add the correct colliders or not?

**Comment by holke** [comment]
Sorry for nagging. I am just confused over all the prs and issues^^

**Comment by maccxs** [comment]
It does.

**Pull request merged**
