### PR TITLE
Smileys with mask

### PR DESCRIPTION
**Pull request by maccxs**
An early christmas present: all smiley pictures with masks and
a mask that could maybe collected during the game. I would also
like to commit the  .xcf gimp file. Any suggestions where to put
those?

### CODE REVIEW

**Comment by holke** [comment]
Regarding the gimp files, please see #69

**Comment by maccxs** [comment]
Should I also put the png-s in the extra folder as long as we do not need them?

**Comment by holke** [comment]
I would not, since we will use them eventually and keeping them in the unity editor makes it way easy to drag and drop them to wherever we want.

**Comment by holke** [comment]
Great commit, thanks for the cool pictures.
As i understand it: You made the mask pics yourself by modifying the smileys and the supermarket is from some website?
Could you include the source for the supermarket somewhere such that we can reference it if needed?
What about the fiesta? (selfmade or not?)

**Comment by maccxs** [comment]
Yes, I modified the smileys with the mask. Updated Readme with picture sources. Also added Covid.19 background which was missing in the sources. Fiesta also from pixabay. I also translated this READM part to English, since everything was mixed

**Pull request merged**
