### PR TITLE
Explain for campaign

### PR DESCRIPTION
**Pull request by maccxs**

### CODE REVIEW

**Comment by maccxs** [comment]
Hi,

I included a screen for explanation of campaign mode. Please give feedback. Did I forgot anything? Does this look good? Spelling? Grammar? :-)

If everything is fine, maybe you can already integreate it in your new button control branch since it is/should be one screen with continue only. I haven't made any proper button controls yet.

**Comment by maccxs** [comment]
grafik
This is what it looks like.

**Comment by maccxs** [comment]
grafik

**Comment by maccxs** [comment]
grafik

**Comment by maccxs** [comment]
grafik

**Comment by maccxs** [comment]
grafik

**Comment by holke** [comment]
Thanks for making these :)
That´s really cool.

In my honest opinion i believe that the info screen for the campaign contains too much.
I rather keep it short and simple to focus the player on the important info.
For example the player status is not really  important in the campaing since every time it changes, the game is lost anyway and the player is informed  that he got Infected...

What do you think of this:

grafik

**Comment by holke** [comment]
I propose i merge these into the button branch and include the Menus,
we can easily update the desing in between and merge the changes in.

**Comment by maccxs** [comment]
> 
> 
> Thanks for making these :)
> That´s really cool.
> 
> In my honest opinion i believe that the info screen for the campaign contains too much.
> I rather keep it short and simple to focus the player on the important info.
> For example the player status is not really important in the campaing since every time it changes, the game is lost anyway and the player is informed that he got Infected...
> 
> What do you think of this:
> 
> grafik

I really really like this. I am not at all set on any of the designs and I am only 80% happy with them anyways so any input is appreciate. Will you push your proposal? Merging into your branch sounds great.

**Comment by holke** [comment]
I integrated the new canvase sand my change into #147

**Comment by holke** [comment]
Closed bc it is integrated id #144

**Pull request closed without merging**
