### PR TITLE
Johannes/end screen

### PR DESCRIPTION
**Pull request by holke**
Implemented an End Screen

The End Screen comes at the end of the game and offers two buttons:

Neustart: Restarts the game
Beenden:  Exits the game

We still need to implement a proper end condition, currently the game just ends after a certain amount of time.
Adjust this time for debugging if it is too short for you.

### CODE REVIEW

**Comment by ghost** [comment]
I don't see any buttons on the end screen. Did you forget to commit them?
Also, the end scene could not be loaded because it was missing from the build settings.

**Comment by holke** [comment]
I seem to have forgotten to push the build settings and an endscene.
Could you please check again?

**Comment by maccxs** [comment]
Hi all, this looks good now to me. The ExitGameButton does nothing at the moment, does it?

**Comment by ghost** [comment]
Looking good! The Exit Button does not work inside the Unity Editor, but I've exported the game as a standalone App and there it works fine. But since the game is going to run in the browser, embedded in a web page... Do we even need an Exit Button? After all, the user can just close their browser window.

**Comment by holke** [comment]
Yes the ExitButton only works when you build the game, no inside of Unity.
And we can certainly remove it later again when we finish the end screen.
I was more playing around and thought of sth that i could quickly implement.

**Pull request merged**
